[build]
  command = ""
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "bcryptjs", "jsonwebtoken"]

# Security headers (CSP) to allow required external assets
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; img-src 'self' data: blob: https:; connect-src 'self' https://cmpmarketinghub.netlify.app https://unpkg.com; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://use.typekit.net https://p.typekit.net https://cdn.jsdelivr.net https://unpkg.com; font-src 'self' https://fonts.gstatic.com https://use.typekit.net https://p.typekit.net data:;"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"

# Redirect API routes to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
